name: upload-docs

on:
  push:
    branches:
      - "master"
      - "release-*"

env:
  PIP_CACHE_PATH: "~/.cache/pip"
  PYTHON_VERSION: "3.8.10"
  PUBLISH_DIR: "./docs/api"
  PUBLISH_BRANCH: "gh-pages"
  DESTINATION_DIR: "api"

jobs:
  upload-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Prepare Python dependencies cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ${{ env.PIP_CACHE_PATH }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install libraries for ubuntu
        run: sudo apt-get install libsndfile1

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Make documents
        shell: bash
        run: |
          python make_docs.py

      - name: Check release
        shell: bash
        run: |
          echo ${{ github.event.ref }} 
          if [[ ${{ github.event.ref }} =~ ^refs/heads/release-* ]]; then
            echo :: set-output name=release::true
          fi

      - name: Copy docs
        if: steps.check-tag.outputs.release == 'true'
        shell: bash
        run: |
          version=$(echo ${{ github.event.ref }} | grep -o -E "([0-9]+\.){1}[0-9]+(\.[0-9]+)?") 
          mkdir -p docs/api/$version
          cp docs/api/index.html docs/api/$version/
          git checkout -- docs/api/index.html 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          destination_dir: ${{ env.DESTINATION_DIR }}
